export const statesByCountry = {
	BR: [
		{ code: "AC", name: { pt: "Acre" } },
		{ code: "AL", name: { pt: "Alagoas" } },
		{ code: "AP", name: { pt: "Amapá" } },
		{ code: "AM", name: { pt: "Amazonas" } },
		{ code: "BA", name: { pt: "Bahia" } },
		{ code: "CE", name: { pt: "Ceará" } },
		{ code: "DF", name: { pt: "Distrito Federal" } },
		{ code: "ES", name: { pt: "Espírito Santo" } },
		{ code: "GO", name: { pt: "Goiás" } },
		{ code: "MA", name: { pt: "Maranhão" } },
		{ code: "MT", name: { pt: "Mato Grosso" } },
		{ code: "MS", name: { pt: "Mato Grosso do Sul" } },
		{ code: "MG", name: { pt: "Minas Gerais" } },
		{ code: "PA", name: { pt: "Pará" } },
		{ code: "PB", name: { pt: "Paraíba" } },
		{ code: "PR", name: { pt: "Paraná" } },
		{ code: "PE", name: { pt: "Pernambuco" } },
		{ code: "PI", name: { pt: "Piauí" } },
		{ code: "RJ", name: { pt: "Rio de Janeiro" } },
		{ code: "RN", name: { pt: "Rio Grande do Norte" } },
		{ code: "RS", name: { pt: "Rio Grande do Sul" } },
		{ code: "RO", name: { pt: "Rondônia" } },
		{ code: "RR", name: { pt: "Roraima" } },
		{ code: "SC", name: { pt: "Santa Catarina" } },
		{ code: "SP", name: { pt: "São Paulo" } },
		{ code: "SE", name: { pt: "Sergipe" } },
		{ code: "TO", name: { pt: "Tocantins" } }
	],
	US: [
		{ code: "AL", name: { en: "Alabama" } },
		{ code: "AK", name: { en: "Alaska" } },
		{ code: "AZ", name: { en: "Arizona" } },
		{ code: "AR", name: { en: "Arkansas" } },
		{ code: "CA", name: { en: "California" } },
		{ code: "CO", name: { en: "Colorado" } },
		{ code: "CT", name: { en: "Connecticut" } },
		{ code: "DE", name: { en: "Delaware" } },
		{ code: "FL", name: { en: "Florida" } },
		{ code: "GA", name: { en: "Georgia" } },
		{ code: "HI", name: { en: "Hawaii" } },
		{ code: "ID", name: { en: "Idaho" } },
		{ code: "IL", name: { en: "Illinois" } },
		{ code: "IN", name: { en: "Indiana" } },
		{ code: "IA", name: { en: "Iowa" } },
		{ code: "KS", name: { en: "Kansas" } },
		{ code: "KY", name: { en: "Kentucky" } },
		{ code: "LA", name: { en: "Louisiana" } },
		{ code: "ME", name: { en: "Maine" } },
		{ code: "MD", name: { en: "Maryland" } },
		{ code: "MA", name: { en: "Massachusetts" } },
		{ code: "MI", name: { en: "Michigan" } },
		{ code: "MN", name: { en: "Minnesota" } },
		{ code: "MS", name: { en: "Mississippi" } },
		{ code: "MO", name: { en: "Missouri" } },
		{ code: "MT", name: { en: "Montana" } },
		{ code: "NE", name: { en: "Nebraska" } },
		{ code: "NV", name: { en: "Nevada" } },
		{ code: "NH", name: { en: "New Hampshire" } },
		{ code: "NJ", name: { en: "New Jersey" } },
		{ code: "NM", name: { en: "New Mexico" } },
		{ code: "NY", name: { en: "New York" } },
		{ code: "NC", name: { en: "North Carolina" } },
		{ code: "ND", name: { en: "North Dakota" } },
		{ code: "OH", name: { en: "Ohio" } },
		{ code: "OK", name: { en: "Oklahoma" } },
		{ code: "OR", name: { en: "Oregon" } },
		{ code: "PA", name: { en: "Pennsylvania" } },
		{ code: "RI", name: { en: "Rhode Island" } },
		{ code: "SC", name: { en: "South Carolina" } },
		{ code: "SD", name: { en: "South Dakota" } },
		{ code: "TN", name: { en: "Tennessee" } },
		{ code: "TX", name: { en: "Texas" } },
		{ code: "UT", name: { en: "Utah" } },
		{ code: "VT", name: { en: "Vermont" } },
		{ code: "VA", name: { en: "Virginia" } },
		{ code: "WA", name: { en: "Washington" } },
		{ code: "WV", name: { en: "West Virginia" } },
		{ code: "WI", name: { en: "Wisconsin" } },
		{ code: "WY", name: { en: "Wyoming" } }
	],
	AR: [
		{ code: "C", name: { es: "Ciudad Autónoma de Buenos Aires" } },
		{ code: "B", name: { es: "Buenos Aires" } },
		{ code: "K", name: { es: "Catamarca" } },
		{ code: "H", name: { es: "Chaco" } },
		{ code: "U", name: { es: "Chubut" } },
		{ code: "X", name: { es: "Córdoba" } },
		{ code: "W", name: { es: "Corrientes" } },
		{ code: "E", name: { es: "Entre Ríos" } },
		{ code: "P", name: { es: "Formosa" } },
		{ code: "Y", name: { es: "Jujuy" } },
		{ code: "L", name: { es: "La Pampa" } },
		{ code: "F", name: { es: "La Rioja" } },
		{ code: "M", name: { es: "Mendoza" } },
		{ code: "N", name: { es: "Misiones" } },
		{ code: "Q", name: { es: "Neuquén" } },
		{ code: "R", name: { es: "Río Negro" } },
		{ code: "A", name: { es: "Salta" } },
		{ code: "J", name: { es: "San Juan" } },
		{ code: "D", name: { es: "San Luis" } },
		{ code: "Z", name: { es: "Santa Cruz" } },
		{ code: "S", name: { es: "Santa Fe" } },
		{ code: "G", name: { es: "Santiago del Estero" } },
		{ code: "V", name: { es: "Tierra del Fuego" } },
		{ code: "T", name: { es: "Tucumán" } }
	]
};
